baseURL = "https://nayon.xyz"
title = "Nayon's den"
theme = "coder"
languageCode = "it"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
    author = "Ernesto"
    info = "Magician"
    description = "Ernesto's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.png"

    favicon_32 = "favicon-32x32.png"
    favicon_16 = "favicon-16x16.png"

    footercontent = "Sup"

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true
    custom_css = []

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/n4y0n/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/n4y0n/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/Ernesto72907917/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about/"